QueryTrafficStatistics:
                  - openconfig/interfaces/interface/state/r1/aggregate : 1tbps
                  - openconfig/interfaces/interface/state/r2/aggregate : 2tbps
                  - openconfig/interfaces/interface/state/r3/aggregate : 3tbps
                  - openconfig/interfaces/interface/state/r4/aggregate : 4tbps
                  - openconfig/interfaces/interface/state/r5/aggregate : 5tbps
                  - openconfig/interfaces/interface/state/r6/aggregate : 6tbps
                  - openconfig/interfaces/interface/state/r7/aggregate : 7tbps
                  - openconfig/interfaces/interface/state/r8/aggregate : 8tbps
                  - openconfig/interfaces/interface/state/r9/aggregate : 9tbps
                  - openconfig/interfaces/interface/state/r10/aggregate : 10tbps
                  - openconfig/interfaces/interface/state/r11/aggregate : 11tbps
                  - openconfig/interfaces/interface/state/r12/aggregate : 12tbps
                  - openconfig/interfaces/interface/state/r13/aggregate : 13tbps
                  - openconfig/interfaces/interface/state/r14/aggregate : 14tbps
                  - openconfig/interfaces/interface/state/r15/aggregate : 15tbps


QuerySystemHealth:
                - CPU_Usage : 35%
                - Memory_Usage : 44%
                - System_State : Good
                - System_Capacity : 115tbps
                - System_Availability: 60% Available

QueryFullInventoryList:
                - Router
                - Server
                - Switch

QueryProductAvailability:
                - Router : 200 Count
                - Server : 75 Count
                - Switch : 100 Count

QueryProductCostAndLeadTime:
                - Router : $1000 and 300 Days
                - Switch : $500 and 250 Days
                - Server : $150 and 100 Days

QueryHigherLeadTimes:
                - Switch
                - Router

QueryHigherCostProducts:
               - Router
